---
namespace: ivansible
name: base
version: 1.0.0

description: Base ansible collection with core settings and modules

authors:
  - Ivan Andreev <ivandeex@gmail.com>

tags:
  - ansible
  - linux
  - common
  - plugins
  - backup
  - server
  - certbot
  - database
  - nginx
  - asterisk

# https://python-semanticversion.readthedocs.io/en/latest/#requirement-specification
# namespace.name: version_range
dependencies: {}

repository: https://github.com/ivansible/base
documentation: https://github.com/ivansible/base
homepage: https://github.com/ivansible/base
issues: https://github.com/ivansible/base/issues

readme: README.md
license: MIT

build_ignore:
  - '*.pyc'
  - '*.tar'
...
