---
dependencies: []

galaxy_info:
  role_name: db_base
  author: "Ivan Andreev"
  description: "common database connection parameters"
  company: "IvanSible"
  license: MIT
  min_ansible_version: 2.5

  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic

  galaxy_tags:
    - linux
    - ansible

  github_branch: master
...
