---
# handlers file for ivansible.asterisk_base
# inherited by all asterisk roles

- name: restart asterisk service (nowait)
  listen: restart asterisk service
  systemd:
    name: asterisk
    state: restarted
  become: yes

- name: restart asterisk service (delay)
  listen: restart asterisk service
  wait_for:
    timeout: "{{ ast_restart_delay }}"

# please use either restart (asterisk_core) or reload (other asterisk roles)
- name: reload asterisk service
  systemd:
    name: asterisk
    state: reloaded
  become: yes
...
