---
# nginx_base/handlers.yml: common nginx handlers for other roles
# Note: handlers will be run in the order they appear in this file

- name: restart nginx service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
  become: true

- name: reload nginx service
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
  become: true

- name: restart uwsgi service
  ansible.builtin.systemd:
    name: uwsgi-emperor
    state: restarted
  become: true
...
