---
# ast_base handlers are inherited by all asterisk roles

- name: restart asterisk service (nowait)
  listen: restart asterisk service
  ansible.builtin.systemd:
    name: asterisk
    state: restarted
  become: true

- name: restart asterisk service (delay)
  listen: restart asterisk service
  ansible.builtin.wait_for:
    timeout: "{{ ast_restart_delay }}"

# Note: please use either restart (ast_core) or reload (other asterisk roles)
#       don't mix!
- name: reload asterisk service
  ansible.builtin.systemd:
    name: asterisk
    state: reloaded
  become: true
...
