---
dependencies: []

galaxy_info:
  role_name: lin_base
  author: "Ivan Andreev"
  description: "common ansible defaults and handlers for other roles"
  company: "IvanSible"
  license: MIT
  min_ansible_version: 2.5

  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic

  galaxy_tags:
    - linux
    - ansible
    - common
...
