---
# lin-base/handlers: common ansible handlers for other roles
# Note: handlers will be run in the order they appear in this file

# This must be the first handler
- name: update system temp files
  # exclude /dev as a workaround for below openvz error:
  # "Failed to openat(/dev/simfs): Operation not permitted"
  ansible.builtin.command: systemd-tmpfiles --create --exclude-prefix /dev
  become: true
  # systemd-tmpfiles files on github runners
  when: lin_systemd_tmpfiles |bool

- name: reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: reload ubuntu firewall
  ansible.builtin.command: ufw reload
  become: true

- name: restart ssh service
  ansible.builtin.systemd:
    name: sshd
    state: restarted
  become: true

- name: restart syslog service
  ansible.builtin.systemd:
    name: syslog
    state: restarted
  become: true

# This must be the last handler
- name: remove temporary play files
  # noqa 302
  ansible.builtin.shell: rm -rfv {{ temp_file }}.*
  become: true
  register: _rm_temp
  changed_when: _rm_temp.stdout.find('removed') != -1
...
