---
# lin-base/handlers: common ansible handlers for other roles
# Note: handlers will be run in the order they appear in this file

# This must be the first handler
- name: update system temp files
  # exclude /dev as a workaround for below openvz error:
  # "Failed to openat(/dev/simfs): Operation not permitted"
  command: systemd-tmpfiles --create --exclude-prefix /dev
  become: yes
  # systemd-tmpfiles files on github runners
  when: lin_systemd_tmpfiles |bool

- name: reload systemd daemon
  systemd:
    daemon_reload: yes
  become: yes

- name: reload ubuntu firewall
  command: ufw reload
  become: yes

- name: restart ssh service
  systemd:
    name: sshd
    state: restarted
  become: yes

# This must be the last handler
- name: remove temporary play files
  # noqa 302
  shell: rm -rfv {{ temp_file }}.*
  become: true
  register: _rm_temp
  changed_when: _rm_temp.stdout.find('removed') != -1
...
