---
# handlers for ivansible.backup_base

- name: remove temporary encrypted database dump
  ansible.builtin.file:
    path: "{{ temp_aes_pgdump.path }}"
    state: absent
  become: true

- name: remove temporary encrypted tarball
  ansible.builtin.file:
    path: "{{ temp_aes_tarball.path }}"
    state: absent
  become: true
...
